urpm-rsync: better support when multiple candidates are reported by urpmq(1)
since urpmq(1) is not really smart, add some logics to choose a candidates
when several choicies are reported for fulfilling one dep.

We also parses /etc/urpmi/prefer.list for helping us to pick up the best
candidates. This makes the behaviour closer to uprpmi one.

diff --git a/urpm-rsync b/urpm-rsync
--- a/urpm-rsync
+++ b/urpm-rsync
@@ -11,7 +11,7 @@ die() {
 }
 
 usage() {
-	warn "$(basename $0) [-v] [-n] [--auto] [--tmpdir=<dir>] [--rsync-exclude=<pattern>] [--rsync-filter-from=<file>...] --list=<file> <SRC> <DST>"
+	warn "$(basename $0) [-v] [-n] [--tmpdir=<dir>] [--rsync-exclude=<pattern>] [--rsync-filter-from=<file>...] --list=<file> <SRC> <DST>"
 	warn
 	warn "  $(basename $0) is a tool to import or update a set of given packages"
 	warn "  and all their dependencies as well. Therefore it can be usefull to create"
@@ -24,7 +24,7 @@ usage() {
 	warn "  Example:"
 	warn
 	warn "    $(basename $0) --rsync-filter-from=excluded.lst --list=packages.lst fbui@abed.mbs:/home/repos/mbs1/x86_64 /tmp/mbs1/"
-	warn "    $(basename $0) --rsync-filter-from=excluded.lst --list=packages.lst rsync://mirrorsync@mirror.mandriva.com/factory/x86_64"
+	warn "    $(basename $0) --rsync-filter-from=excluded.lst --list=packages.lst rsync://mirrorsync@mirror.mandriva.com/factory/x86_64 /tmp/factory"
 	warn
 	warn "  Sample of 'excluded.lst':"
 	warn
@@ -43,7 +43,6 @@ usage() {
 	exit 1
 }
 
-auto_deps=false
 tmpdir=
 package_list=
 dry_run=
@@ -54,7 +53,6 @@ verbose=
 while
 
 	case $1 in
-	--auto)			auto_deps=true ;;
 	--list=*)		package_list=${1#--list=} ;;
 	--tmpdir=*)		tmpdir=${1#--tmpdir=} ;;
 	--rsync-exclude=*)	exclude_patterns+=(--exclude=${1#*=}) ;;
@@ -125,6 +123,27 @@ if test ${#packages[*]} -eq 0; then
 fi
 
 #
+# Import preferred packages from /etc/urpmi/prefer.list and
+# /etc/urpmi/prefer.vendor.list since urpmq(1) doesn't. The manpage
+# claims about a --prefer option which has no effects AFAICS.
+#
+declare -A preferred_packages
+declare -a preferred_regexp_packages
+
+for f in /etc/urpmi/prefer.{,vendor.}list; do
+	test -r $f || continue
+
+	while read p; do
+		case $p in
+		'')	continue ;;
+		\#*)	continue ;;
+		/*/)	preferred_regexp_package+=(${p:1:-1}) ;;
+		*)	preferred_packages[$p]=$p
+		esac
+	done <$f
+done
+
+#
 # Temporary directory.
 #
 cleanup_on_exit() {
@@ -168,48 +187,95 @@ rsync://*)	stupid_urpm_url=$distrib ;;
 *)		die "You must use an absolute path for specifying distribution URL."
 esac
 
-# urpmq print some debug outputs on stderr if ssh protocol is used...
+#
+# This gets the list of all dependencies of the specified
+# packages. 'root' packages are also included in the returned list.
+#
+# urpmq(1) can report several possibilites/candidates for one specific
+# dep. The items of the list are separeted by '|' char in that
+# case. Unfortunately the list doesn't seem to be ordered, so the
+# first item is not the one urpmi would select when --auto is passed.
+#
+# Note also for those candidates, their deps are not shown, so we have
+# to restart a deps discovery for them.
+#
+# urpmq(1) has also the --prefer option but it has absolutely no
+# effects when tested... oh well...
+#
+select_candidate () {
+	for c; do
+		if test ${preferred_packages[$c]}; then
+			echo $c
+			return
+		fi
+	done
+	for c; do
+		for re in "${preferred_regexp_package[@]}"; do
+			if [[ $c =~ $re ]]; then
+				echo $c
+				return
+			fi
+		done
+	done
+	echo $1
+}
+
+_get_all_dependencies () {
+	# urpmq(1) prints some debug outputs on stderr if ssh protocol
+	# is used...
+	urpmq --use-distrib $stupid_urpm_url \
+	      --requires-recursive "$@" \
+	      >$tmpdir/deps.lst 2>$tmpdir/urpmq-stderr.log
+
+	# urpmq is boggus: it can return 0 even when failing so try
+	# to handle the case gracefully.
+	if test $? -ne 0 || ! test -s $tmpdir/deps.lst; then
+		warn "Failed to retrieve dependencies for given packages."
+		warn "Here's the log of urpmq that might help you to resolve the issue:"
+		warn
+		cat >&2 $tmpdir/urpmq-stderr.log
+		exit 1
+	fi
+
+	cat $tmpdir/deps.lst | sort | uniq >$tmpdir/deps-sorted.lst
+	# Return the deps with no ambiguity.
+	sed -e '/.*|.*/d' $tmpdir/deps-sorted.lst
+
+	# Handle multiple candidates fulfilling one dep.
+	grep -q -F '|' $tmpdir/deps-sorted.lst ||
+		return
+
+	sed -n '/.*|.*/p' $tmpdir/deps-sorted.lst | \
+		while IFS='|' read -a candidates
+		do
+			for c in $(select_candidate "${candidates[@]}"); do
+				# Avoid cyclic deps.
+				grep -q "$c\$" $tmpdir/deps-visited.lst &&
+					continue
+				echo "$c" >>$tmpdir/deps-visited.lst
+				_get_all_dependencies $c
+			done
+		done
+}
+
+get_all_dependencies () {
+	> $tmpdir/deps-visited.lst
+	_get_all_dependencies "$@" | sort | uniq
+}
+
 echo "Processing dependencies..."
-urpmq --use-distrib $stupid_urpm_url --requires-recursive "${packages[@]}" >$tmpdir/deps.lst 2>$tmpdir/urpmq-stderr.log
-
-# urpmq is boggus: it returns 0 even when failing so add a sanity
-# check.
-if test $? -ne 0 || ! test -s $tmpdir/deps.lst; then
-	warn "Failed to retrieve dependencies for given packages."
-	warn "Here's the log of urpmq that might help you to resolve the issue:"
-	warn
-	cat >&2 $tmpdir/urpmq-stderr.log
-	exit 1
-fi
-
-cat $tmpdir/deps.lst | sort | uniq >$tmpdir/deps-sorted.lst
-
-#
-# Make sure there's no multiple choices for a given dep.
-#
-if $auto_deps; then
-	# Pick up the first choice.
-	sed -ri 's/([^|]*).*/\1/' $tmpdir/deps-sorted.lst
-
-elif grep -q -F '|' $tmpdir/deps-sorted.lst; then
-	warn "Multiple choices are available for one provide."
-	warn "Please, add your choice(s) in the package list to import or use"
-	warn "the --auto option to select the first candidate automatically."
-	warn
-	grep -F '|' $tmpdir/deps-sorted.lst
-	exit 1
-fi
+get_all_dependencies "${packages[@]}" >$tmpdir/dependencies-sorted.lst
 
 #
 # Generate rsync filter rules and use them to sync the repo.
 #
-for p in $(< $tmpdir/deps-sorted.lst); do
+for p in $(< $tmpdir/dependencies-sorted.lst); do
 	echo "+ $p-[[:digit:]]*.rpm"
-done >$tmpdir/rsync-packages-filter
+done >$tmpdir/rsync-filter-rpm
 
 cat >$tmpdir/rsync-filter-packages<<EOF
 ${filter_from:+. $filter_from}
-. $tmpdir/rsync-packages-filter
+. $tmpdir/rsync-filter-rpm
 - *.rpm
 - media_info/*
 EOF
